# Assignment 2 
---
Name        : **Sachin Kohli**                  
Roll number : **20123** 

---

## What are Data structures, and data types in python?
---
#### Data structures are basically structures which can hold some data together. In other words, they are used to store a collection of related data. Example - list, tuple, dictionary and set.
#### A data type or simply type is an attribute of data which tells the compiler the form of data.  Example - int, string, float, etc.

## Program 1: How to declare vectors, lists in python, Execute with some basic examples, also state about the size and shape and dimensions of these. Perform arithmetic operations on these vectors and lists. Write the proper commands.

### List

In [1]:
# Normal List of size 3
list1 = [1, 2, 3]
list2 = [10, 11, 12]

# List of Lists
list3 = [[1], [2], [3]]

print(list1)
print(list2)
print(list3)

In [2]:
# Addition of Lists. This just concatenate the two list elements into one.
addLi = list1 + list2
print(addLi)

[1, 2, 3, 10, 11, 12]


In [3]:
# Multiplication of List with constant say 10 creates 10 copies of each elements in the list.
mulLi = list1 * 3
print(mulLi);

[1, 2, 3, 1, 2, 3, 1, 2, 3]


### Vectors

In [4]:
import numpy as np

# Horizontal Vector of size 3
vector1 = np.array(list1)
vector2 = np.array(list2)

# Vertical Vector of size 3
vector3 = np.array(list3)

print(vector1)
print(vector2)
print(vector3)

[1 2 3]
[10 11 12]
[[1]
 [2]
 [3]]


In [5]:
len(vector1)

3

In [6]:
vector1.shape

(3,)

In [7]:
# Addition of two vectors.
addVec = vector1 + vector2
print(addVec);

[11 13 15]


In [8]:
# Subtraction of two Vectors.
subVec = vector2 - vector1
print(subVec)

[9 9 9]


In [9]:
# Multiplication of two Vectors
mulVec = vector1 * vector2
print("Multiplication : " + str(mulVec))

Multiplication : [10 22 36]


In [10]:
# Division of two Vectors
divVec = vector2 / vector1
print("Division : " + str(divVec))

Division : [10.   5.5  4. ]


In [11]:
# Dot product of Vectors
dotProduct = vector1.dot(vector2)
print(dotProduct)

68


In [12]:
# Scalar Multiplication
scalar = 7
sMul = vector1 * scalar
print(sMul)

[ 7 14 21]


##  Program 2: Implement vectors and matrix operations using numpy, such as addition, subtraction, multiplication, and inverse, transpose of the matrix.

### Matrix

In [13]:
matrix_1 = np.array([[1, 0 , 0], [4 ,0 ,6], [0, 2, 9]]) 
print(matrix_1.shape)

matrix_2 = np.array([[1, 5, 9], [4, 2, 3], [7, 3, 1]])
print(matrix_2.shape)

(3, 3)
(3, 3)


In [14]:
matrix_1

array([[1, 0, 0],
       [4, 0, 6],
       [0, 2, 9]])

In [15]:
matrix_2

array([[1, 5, 9],
       [4, 2, 3],
       [7, 3, 1]])

In [16]:
# Addition
matrix_1 + matrix_2

array([[ 2,  5,  9],
       [ 8,  2,  9],
       [ 7,  5, 10]])

In [17]:
# Subtraction
matrix_1 - matrix_2

array([[ 0, -5, -9],
       [ 0, -2,  3],
       [-7, -1,  8]])

In [18]:
# Normal Multiplication
matrix_1 * matrix_2

array([[ 1,  0,  0],
       [16,  0, 18],
       [ 0,  6,  9]])

In [19]:
# Actual Matrix Multiplication
matrix_1.dot(matrix_2)

array([[ 1,  5,  9],
       [46, 38, 42],
       [71, 31, 15]])

In [20]:
# Determinant if non-zero then inverse EXISTS.
np.linalg.det(matrix_1)

-11.999999999999995

In [21]:
# Inverse 
inverse1 = np.linalg.inv(matrix_1)
inverse1

array([[ 1.        ,  0.        ,  0.        ],
       [ 3.        , -0.75      ,  0.5       ],
       [-0.66666667,  0.16666667, -0.        ]])

In [22]:
# Should be Identity Matix
matrix_1.dot(inverse1)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [23]:
# Transpose using function
np.transpose(matrix_1)

array([[1, 4, 0],
       [0, 0, 2],
       [0, 6, 9]])

In [24]:
# Transpose using Algo
trans = np.arange(9)
trans = trans.reshape(3,3)

for i in range(len(matrix_1)):
    for j in range(len(matrix_1[0])):
        trans[j][i] = matrix_1[i][j]

print(trans)
        


[[1 4 0]
 [0 0 2]
 [0 6 9]]


## Program 3.  (i) Write a program that check that two matrices are identical.  (ii) check that the matrices are the mirror image of each other.

In [25]:
# If matrices given are Identical
def Iden(A, B):
    flag = True
    if A.shape == B.shape:
        for i in range(len(A)):
            for j in range(len(A[0])):
                if A[i][j] != B[i][j]:
                    flag = False
                    break
    else:
        flag = False     
    return flag;
    
A = np.array([[1,2],[2,1]])
B = np.array([[1,2],[2,1]])

Iden(A,B)

True

In [26]:
# If given Matrices are Mirror
# Mirror is simply Transpose os a matrix
# We can do it with the algorithm used for transpose

def Mirror(matrix):
    for i in range(len(matrix)):
        for j in range(i+1):
            temp = matrix[j][i]
            matrix[j][i] = matrix[i][j]
            matrix[i][j] = temp
            
    return matrix

mat = np.array([[1, 2 , 3], [4 ,5 ,6], [7, 8, 9]]) 
print(mat)
Mirror(mat)
    

        

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

## Program 4: import and export data file (csv file) using data frame and perform the data frame operations using pandas.

In [27]:
# Importing CSV file

import pandas as pd
df = pd.read_csv("cities.csv")
df.head(8)

LatD   "LatM"   "LatS"  "NS"   "LonD"   "LonM"   "LonS"  "EW"  \
0    41        5       59   "N"       80       39        0   "W"   
1    42       52       48   "N"       97       23       23   "W"   
2    46       35       59   "N"      120       30       36   "W"   
3    42       16       12   "N"       71       48        0   "W"   
4    43       37       48   "N"       89       46       11   "W"   
5    36        5       59   "N"       80       15        0   "W"   
6    49       52       48   "N"       97        9        0   "W"   
7    39       11       23   "N"       78        9       36   "W"   

               "City"  "State"  
0        "Youngstown"       OH  
1           "Yankton"       SD  
2            "Yakima"       WA  
3         "Worcester"       MA  
4   "Wisconsin Dells"       WI  
5     "Winston-Salem"       NC  
6          "Winnipeg"       MB  
7        "Winchester"       VA

In [32]:
# Export Dataframe as CSV file

names = ["Arnub", "Binod", "Chetan"]
age = [32, 49, 19]
sex = ['M', 'M', 'M']

dict = {"NAME" : names, "AGE" : age, "SEX" : sex}
df2 = pd.DataFrame(dict)

df2.to_csv('new.csv', index = False) 

print(df2)

     NAME  AGE SEX
0   Arnub   32   M
1   Binod   49   M
2  Chetan   19   M
